### ISSUE TITLE
Switching issue

### ISSUE THREAD

**Issue by w-sz** [dsills22/sticky-states-ui-router-1-js#2]
Hi, thank you for your work! Unfortunately for me this do not work. 

When you switch from sticky state to other state (which is not sticky) is fine, but when you want to switch from sticky state to other sticky state, the url change but view not.

**Comment by dsills22** [comment]
Hi @witoldszpur, I recently updated the code with some fixes (around 30 min ago), have you tried the newest code?

**Comment by witoldszpur** [comment]
yes I saw, but same result.

**Comment by dsills22** [comment]
OK --- are you using the same ui router version as I am? (1.0.0-beta.3) Also, sticky states requires named views, which, if missing, could be causing some issues. 

My setup is like this: 

home: { name: "home", component: "home", url: "/home", views: { "": "home" } },

child1: { name: "child1", url: "/child1", display: "child1", parent: "home", views: { child1: "child1" }, sticky: true },

child2: { name: "child2", url: "/child2", display: "child2", parent: "home", views: { child2: "child2" }, sticky: true },

Where views: { child2: "child2" } means the view child2 uses the component "child2". 

In my "home" component, I have, among other things: 

div ui-view="child1"
div ui-view="child2"

And my child components look like: 

    .component("child1", {
        template: "<div ng-show=\"!isInactive\" data-some-directive></div>",
        controller: ["$scope", "StickyStatesData", function($scope, StickyStatesData) {
            $scope.$on(StickyStatesData.inactiveEvent, function(event, inactiveMap) {
                $scope.isInactive = !!inactiveMap.child1;
            });
        }]
    })

    .component("child2", {
        template: "<div ng-show=\"!isInactive\" data-some-directive></div>",
        controller: ["$scope", "StickyStatesData", function($scope, StickyStatesData) {
            $scope.$on(StickyStatesData.inactiveEvent, function(event, inactiveMap) {
                $scope.isInactive = !!inactiveMap.child2;
            });
        }]
    })

This works for me for switching between the sticky states child1 and child2. I also just tested with a child3 that is not sticky and I could switch between child1, 2, 3 without any issues (and child3, the non-sticky one, indeed recreated itself but child1, 2 did not).

If you still have issues, mind creating a plunker I can take a look at?

**Comment by dsills22** [comment]
FYI, in case you haven't seen it, I did find an issue and fix it where switching states was causing a state to be entered and inactivated at the same time. This is basically an issue that occurs when the state mapping needs some re-working, which was my case. But nevertheless I made a fix for it, maybe it helps your situation. If you're still having the same issue though then I can help out with via plunker.

**Comment by witoldszpur** [comment]
Hi, a great thx for your work. Unfortunately still not working. I had what you mention before, maybe because my routing structure is big and complicated.

**Comment by dsills22** [comment]
Do you happen to use dynamic states? I found an issue that matches your description while using dynamic states and added a fix, maybe it helps you. You also might just check the project every so often since I update it anytime I find something (I'm actively using this code so I have to fix any issues I run into)
